version: '3.8'

services:
  app:
    build: .
    volumes:
      - app_data:/app
    container_name: restapi
    env_file: ./.env
    ports:
      - "3002:3002"
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    depends_on:
      - db
    networks:
      - restapi-nt

  db:
    image: postgres
    volumes:
      - db_data:/var/lib/postgresql/data 
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    env_file: ./.env
    ports:
      - "5432:5432"
    networks:
      - restapi-nt

networks:
  restapi-nt:
    driver: bridge

volumes:
  app_data:  # Mendefinisikan volume untuk aplikasi
  db_data:   # Mendefinisikan volume untuk database